# Generated by Django 6.0.1 on 2026-03-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
