# Generated by Django 6.0.1 on 2026-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_certificate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
