# Generated by Django 6.0.1 on 2026-04-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_remove_userprogress_score_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='course',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
