"""
Django settings for moodproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1$%7g=&p^-&xtdms6z4gmlq0jn#z)sbb)r-1#nk+z93*868)&v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:52726',
    'http://localhost:52726',
    'http://127.0.0.1:62125',
    'http://localhost:62125',
    'http://127.0.0.1:51217',
    'http://localhost:51217',
    # Allow any localhost / 127.0.0.1 port (covers the browser-preview proxy)
    'http://127.0.0.1:*',
    'http://localhost:*',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Dark sidebar/navbar theme — must come BEFORE django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'learning'
]

MIDDLEWARE = [
    'moodproject.dev_csrf.ForceUtf8ContentTypeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'moodproject.dev_csrf.DevPermissiveCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


ROOT_URLCONF = 'moodproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'learning' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moodproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []
    
   


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Where to go after a successful login
LOGIN_REDIRECT_URL = 'index'  # Use the name 'index' instead of '/'

# Where to go after logging out
LOGOUT_REDIRECT_URL = 'login' 

# The URL where @login_required redirects unauthenticated users
LOGIN_URL = 'login'  # Use the named URL pattern

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 2. Add the Email configuration here
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'Moodbasedelearning@gmail.com'  
EMAIL_HOST_PASSWORD = 'yjgo hxra muvk swkj'

DEFAULT_FROM_EMAIL = 'Mood Learning <Moodbasedelearning@gmail.com>'

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===== Jazzmin admin theme =====
JAZZMIN_SETTINGS = {
    "site_title": "Mood Learning Admin",
    "site_header": "Mood Learning",
    "site_brand": "Mood Learning",
    "site_logo": None,
    "custom_css": "admin/custom_admin.css",
    "welcome_sign": "Welcome to the Mood Learning admin console",
    "copyright": "Mood Learning © 2026",
    "search_model": ["auth.User", "learning.Course"],

    # Top menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin_dashboard", "permissions": ["auth.view_user"]},
        {"name": "Main Site", "url": "/", "new_window": False},
        {"model": "auth.User"},
        {"app": "learning"},
    ],

    # User menu (top right)
    "usermenu_links": [
        {"name": "Change password", "url": "change_password"},
        {"model": "auth.user"},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "learning"],

    # Per-model icons (Font Awesome free)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "learning.Course": "fas fa-book-open",
        "learning.Stream": "fas fa-stream",
        "learning.Video": "fas fa-video",
        "learning.Quiz": "fas fa-question-circle",
        "learning.QuizRecording": "fas fa-film",
        "learning.Certificate": "fas fa-award",
        "learning.Enrollment": "fas fa-user-check",
        "learning.Assignment": "fas fa-tasks",
        "learning.AssignmentSubmission": "fas fa-file-upload",
        "learning.UserProgress": "fas fa-chart-line",
        "learning.MoodLog": "fas fa-smile",
        "learning.StudentMood": "fas fa-grin-stars",
        "learning.ChatMessage": "fas fa-comments",
        "learning.VideoProgress": "fas fa-play-circle",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Related modal popups
    "related_modal_active": True,

    # UI tweaks
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-indigo",
    "navbar": "navbar-dark navbar-indigo",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}


RAZORPAY_KEY_ID = 'rzp_test_SlK3T5r4KhfPYX'
RAZORPAY_KEY_SECRET = 'cOvWxy52Y3zr11x9kUl2j2OF'

# Admin UPI ID for receiving payments
ADMIN_UPI_ID = '9353818194@kotakbank'



